export type Questionario = {
  tipo: string;
  cor: string;
  perguntas: string[];
};

export const questionario: Questionario[] = [
  {
    tipo: "Saúde Física",
    cor: "#06C",
    perguntas: [
      "De forma geral, me sinto em boa forma física comparando a outras pessoas de minha faixa etária.",
      "Pratico pelo menos 30 minutos de atividade física, 3 vezes por semana.",
      "Minha dieta é balanceada e completa, incluindo uma grande quantidade de fibras, frutas e vegetais.",
      "Procuro manter um peso adequado para minha altura e faixa etária.",
      "Não fumo.",
      "Não bebo ou bebo socialmente.",
      "Durmo o suficiente para reparar meu cansaço.",
      "Consulto um médico clínico e realizo exames preventivos pelo menos uma vez ao ano.",
      "Uso cinto de segurança e respeito os limites de velocidade quando estou dirigindo.",
      "Tomo cuidados apropriados para a segurança pessoal dentro da minha casa.",
    ],
  },
  {
    tipo: "Saúde Emocional",
    cor: "#4CB140",
    perguntas: [
      "Estou satisfeito(a) comigo mesmo.",
      "Encontro maneiras adequadas de expressar minha emoção.",
      "Procuro me comunicar de forma verdadeira e direta com as outras pessoas.",
      "Sou uma pessoa bem humorada.",
      "Gosto de estar sozinho(a) de vez em quando.",
      "Peço ajuda quando necessário.",
      "Sou capaz de dizer NÂO sem me sentir culpado(a).",
      "Sei pedir desculpas quando erro.",
      "Costumo elogiar os feitos positivos de outras pessoas.",
      "Sou capaz de relaxar sem o uso de drogas ou medicamentos.",
    ],
  },
  {
    tipo: "Saúde Familiar",
    cor: "#009596",
    perguntas: [
      "Estou satisfeito(a) com o tipo de relação que estabeleço com a minha família (pais, filhos, etc). Se não tenho, estou satisfeito(a) sozinho.",
      "Tenho um parceiro(a) e estou satisfeito(a) com a nossa relação.",
      "Diariamente dedico parte do meu tempo à minha família.",
      "Gosto de conviver com a minha família nos finais de semana.",
      "Ajudo minha família (pais, irmãos, tios e filhos) em termos financeiros quando eles precisam.",
      "Ajudo minha família afetivamente (por intermédio da minha presença e conselhos), sempre que eles precisam.",
      "Gosto de organizar encontros e festas de aniversário com a família para incentivar a união familiar.",
      "Convivo com minha família o tempo que julgo necessário.",
      "Nas férias, minha família costuma se reunir para usufruir de bons momentos juntos.",
      "Já cuidei, ou cuidarei dos meus pais em sua velhice, com boa vontade e disposição.",
    ],
  },
  {
    tipo: "Saúde Social",
    cor: "#3C3D99",
    perguntas: [
      "Sou capaz de desenvolver relacionamentos próximos e estáveis.",
      "Com meus amigos, costumamos realizar ações sociais voluntárias em prol de pessoas necessitadas.",
      "Tenho um grupo de amigos(as) e mantenho uma relação próxima e frequente com eles/elas (festas de aniversários, saídas, encontros e passeios).",
      "Estou satisfeito(a) com o tipo de relação que mantenho com meus colegas e superiores no trabalho.",
      "Tenhopessoascomquemdesabafarquandoestoutensaouansiosa.",
      "Tenho uma interação ativa com meus amigos e familiares no dia a dia.",
      "Meu dia a dia é uma fonte de prazer para mim, ao lado das pessoas com as quais convivo.",
      "Realizo atividades de lazer junto com amigos no domingo e jogos diversos prazerosos.",
      "Exerço um papel social dentro da comunidade onde vivo.",
      "Procuro, sempre que possível, estar em contato com a natureza.",
    ],
  },
  {
    tipo: "Saúde Financeira",
    cor: "#F46FDA",
    perguntas: [
      "Estou satisfeito(a) com meu salário e/ou com o que eu ganho pelo meu trabalho.",
      "Consigo organizar minha vida financeira e mantenho minhas contas em dia.",
      "Procuro guardar parte do que ganho na poupança ou em outro investimento para quando eu precisar de uma verba extra.",
      "Não costumo pegar dinheiro emprestado no Banco, pois os juros são altos.",
      "Faço prestações para comprar objetos de valor quando tenho previsão de poder pagá-las.",
      "Não gasto em supérfluos quando não tenho dinheiro sobrando.",
      "Costumo comprar à vista, não faço prestações, nem cheques pré- datados para compras do dia a dia.",
      "Quando recebo algum dinheiro extra, procuro guardar uma parte na poupança ou investimento.",
      "Sou capaz de dizer não empresto para algum amigo ou parente quando não tenho condições de arcar com os valores.",
      "Não costumo entrar no saldo negativo do banco.",
    ],
  },
  {
    tipo: "Saúde Intelectual",
    cor: "#8F4700",
    perguntas: [
      "Mantenho um contínuo crescimento na área intelectual.",
      "Concentro-me facilmente.",
      "Uso a criatividade em todas as áreas de minha vida.",
      "Gosto de ler e a leitura faz parte do meu dia a dia.",
      "Desenvolvo pelo menos uma atividade (hobbie) que eu gosto, mas não me sinto obrigada a fazer.",
      "Gosto de me expressar por meio da dança, arte, música e encontro tempo para fazer isso.",
      "Sou curioso(a) e novidades são uma fonte de motivação para mim.",
      "Interesso-me por diversos assuntos relacionados à minha vida profissional.",
      "Participo espontaneamente de grupos de estudos, palestras e debates.",
      "Gosto de partilhar conhecimentos e ouvir outros pontos de vista a respeito de assuntos que me interessam.",
    ],
  },
  {
    tipo: "Saúde Profissional",
    cor: "#15BFCC",
    perguntas: [
      "Gosto do meu trabalho.",
      "Estou satisfeito(a) com o tempo que meu trabalho/carreira requer na minha vida.",
      "Minha carga de atividade profissional é sempre planejada.",
      "Sinto que completei todas as tarefas do dia quando saio do meu emprego.",
      "Procuro aprender com os erros.",
      "Estou satisfeito(a) com a minha habilidade de tomar decisões.",
      "Considero-me organizado(a).",
      "Meu trabalho é recompensador para mim.",
      "Estou orgulhoso(a) de minhas conquistas profissionais.",
      "Tenho objetivos e planos para a minha carreira e pós-carreira.      ",
    ],
  },
  {
    tipo: "Saúde Espiritual",
    cor: "#C46100",
    perguntas: [
      "Considero-me uma pessoa feliz.",
      "Estou em paz comigo mesmo(a).",
      "Estou satisfeito(a) com minha vida espiritual.",
      "Sinto-me equilibrado(a), guiada por meus valores pessoais.",
      "Proponho objetivos realistas para a minha vida.",
      "Estou satisfeito(a) com o progresso dos meus objetivos.",
      "Me conecto com uma força maior do que eu que tem um significado pra mim.",
      "Sou tolerante com as crenças e valores dos outros.",
      "Gosto de praticar algum tipo de disciplina espiritual e sinto a presença de alguma “força” que guia minha passagem pela vida.",
      "Busco realizar atividades de caráter voluntário e isto me faz um bem espiritual.",
    ],
  },
];
